version: '3.8'

services:
  app:
    container_name: unolo-app
    build: .
    ports:
      - "4003:4003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/unolo
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    container_name: unolo-mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: